Repository Azure/counterfit, pull requests merged in 2022-11, with the labels that each got.

#58 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: Type: Feature

#61 Users/rdheekonda/update read me
  README.md
  counterfit/core/targets.py
  counterfit/reporting/image.py
  infrastructure/Dockerfile
  infrastructure/DockerfileCounterfitJupyterlab.dockerfile
  infrastructure/DockerfileJupyterhubShell.dockerfile
  infrastructure/azuredeploy.json
  static/counterfit_arm_deployment.png
  static/counterfit_container_aci_terminal.png
  static/counterfit_container_instance.png
  static/counterfit_resource_group.png
  static/counterfit_terminal_cmd.PNG
Labels: Type: Documentation, Type: Feature

#60 Fixed some warning messages and removed commented code
  examples/terminal/commands/list.py
  examples/terminal/commands/predict.py
  examples/terminal/commands/reload.py
  examples/terminal/commands/run.py
  examples/terminal/commands/save.py
  examples/terminal/core/terminal.py
Labels: Type: Documentation
